### ISSUE TITLE
不能用了好像，4.1那个版本，求楼主修复

### ISSUE THREAD

**Issue by cnkant** [iicovo/momo-share#1]

**Comment by iicovo** [comment]
哪里出了问题？我这里还是可以用的。这用的都是网上找的免费代理，很不稳定的。如果你有好的代理ip可以自行更改码的。
还有一点，我用的是Python3.7版本写的，用其他版本可能会出现意料之外的问题。

**Comment by iicovo** [comment]
建议你用3.7版本打包。也可以将你的代码发到我的邮箱“iicovo@88.com”，我有空帮你打包一下。
这个问题我猜测可能是代理地址问题。我的代码里，抓取的代理有https的，我没有把抓取的代理地址清理，统一保存成了http地址。
